import = ["~/.config/alacritty/cobalt2.toml"]
[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Hasklug Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 25
