#!/bin/sh

# basic settings
# enforce tiled layout by default
# force tiled layout on all desktops on all monitors


bspc config border_width 1
bspc config window_gap 15
bspc config split_ratio 0.52
bspc config focus_follows_pointer true
bspc config top_padding 15


# sane defaults
bspc config single_monocle true
bspc config gapless_monocle false

# floating rules
bspc rule -a Ulauncher state=floating center=true
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Gnome-calculator state=floating

# monitor layout (arandr)
/home/akash/.config/bspwm/monitors.sh &
sleep 1

# monitor detection & desktop assignment
for m in $(bspc query -M); do
	bspc monitor "$m" -d 1 2 3 4 5 6
	for d in $(bspc query -D -m "$m"); do
		bspc desktop "$d" -l tiled
	done
done
# for m in $(bspc query -M); do
# done

# autostart core services
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x blueman-applet >/dev/null || blueman-applet &
pgrep -x picom >/dev/null || picom &
pgrep -x qbittorrent >/dev/null || qbittorrent &
pgrep -x bluemail > /dev/null || /opt/BlueMail/bluemail --no-sandbox %U &

# Idle lock + DPMS
pgrep -x xss-lock >/dev/null || xss-lock --transfer-sleep-lock -- i3lock -c 1e1e2e &
# Suspend after long idle (X11, per-session)
pgrep -x xautolock >/dev/null || \
xautolock \
  -time 30 \
  -locker "systemctl suspend" \
  -detectsleep &




# DPMS timings (seconds)
# Setting Idle Timeout
xset s 600
# Setting standby, suspend, off timeouts for screen
xset dpms 660 660 720



# polybar on all monitors (idempotent, with theming)
. ~/.config/themer/colors.sh

for m in $(polybar --list-monitors | cut -d: -f1); do
  pgrep -f "polybar.*$m.*main" >/dev/null || \
  MONITOR="$m" \
  polybar main &
done

# wallpaper
feh --bg-scale "$HOME/.config/bspwm/terrain.jpg" &

# cursor + X defaults
xsetroot -cursor_name left_ptr

# rofi colors
"$HOME/.config/rofi/rofi-color-generator.sh"


